[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Stryd PWA redirects
[[redirects]]
  from = "/stryd/*"
  to = "/stryd/index.html"
  status = 200

# Main site redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"